# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: 'docker build -f Dockerfile -t tp1docker .'
      - run: 'docker run -d -p 8081:8080 tp1docker'