# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: 
          name: docker build en fonction du Dockerfile
          command: 'docker build -f Dockerfile -t tp1docker .'
      - run: 
          name: docker run sur le port 8080
          command: 'docker run -d -p 8080:8080 tp1docker'
      - run: 
          name: Test curl 
          command: 'curl http://localhost:8080/' 